<a href="https://colab.research.google.com/github/kanikaguptakk/learn_py/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
'''
list can store only 1 D array(float,integer,string,boolean) but importing numpy array we can store multidimensional array
'''
import numpy as np
a=np.array([3,4,5,6])
print(a)

b=np.array([[4,3,5,6],[5,6,7,8]])
print(b)

c=np.array([[3,4,6,7],[5,6,7,8],[5,6,7,8]])
print(c)

'''
a is a numpy n-dimensional array

'''
# type(a)

'''
size=number of elements in that array
'''
# print(a.size)
# print(b.size)
# print(c.size)

'''
shape=number of rows and columns
'''
# print(a.shape)
# print(b.shape)
# print(c.shape)

'''dtype=type of data present in the array
'''
# print(a.dtype)
# print(b.dtype)
# print(c.dtype)

# d=np.array([[4.5,2.4,5,4],[1.0,5,6,7],[7,8,9,10]])
# print(d.dtype)
# print(d.transpose())

'''
np.empty((rows,cols),dtype) where (rows,cols) is tuple-to get an empty array of random data
'''
# p=np.empty((3,5),dtype=float)
# print(p)
# q=np.empty((2,3),dtype=int)
# print(q)


'''
np.ones((rows,cols),dtype=float(bydefault))-to get an array consisting of only 1's (float data type)
'''
# g=np.ones((4,3))
# print(g)
# e=np.ones((4,5),dtype=int)
# print(e)

'''
np.zeros((rows,cols),dtype=flaot(bydefault))-to get an array consisting of only o's(flaot data type)
**zeros not zeroes**
'''
# t=np.zeros((4,5))
# print(t)
# f=np.zeros((6,4),dtype=int)
# print(f)

# k=np.zeros((4,5),dtype=bool)
# print(k)
# g=np.zeros((3,4),dtype=str)
# print(g)
# h=np.ones((5,6),dtype=bool)
# print(h)
'''
np.arange(start,end,step)
**arange not arrange**

'''
# r=np.arange(3,7,2)
# print(r)
t=np.arange(4,77,5)
print(t)
'''
arr.reshape((rows,cols))-to convert into a matrix
'''
t=t.reshape((3,5))
print(t)

'''
arr.flatten()-reverse process of reshape
'''
t=t.flatten()
print(t)

t=t.reshape((5,3))
print(t)

t=t.ravel()
print(t)
'''
arr.ravel()
ravel                                        vs  flatten
returns only view of original array              returns copy of origianl array

'''



[3 4 5 6]
[[4 3 5 6]
 [5 6 7 8]]
[[3 4 6 7]
 [5 6 7 8]
 [5 6 7 8]]
[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74]
[[ 4  9 14 19 24]
 [29 34 39 44 49]
 [54 59 64 69 74]]
[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74]
[[ 4  9 14]
 [19 24 29]
 [34 39 44]
 [49 54 59]
 [64 69 74]]
[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74]


'\narr.ravel()\nravel                                        vs  flatten\nreturns only view of original array              returns copy of origianl array\n\n'